name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}} #create this variable
            heroku_app_name: "pruebadevopp" #Must be unique in Heroku
            heroku_email: "tuburce@gmail.com"
    
